name: "jaffle-shop-classic"

config-version: 2
version: "0.1"

profile: "jaffle-shop-classic"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  jaffle-shop-classic:
    materialized: table
    staging:
      materialized: view
